services:
  aqm_etl_flow_prefect:
    image: laggerkrd/air_quality_monitor
    env_file:
      - .env
    restart: always

  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always

  metabase:
    image: metabase/metabase
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: always

volumes:
  postgres-data: